//! GPU acceleration module for Weber electrodynamics simulation.
//!
//! Uses cudarc (safe Rust CUDA bindings) to dispatch double-double arithmetic
//! kernels compiled to PTX by build.rs.
//!
//! Architecture:
//!   - GpuContext: manages device, buffers, loaded kernel modules
//!   - Decimal ↔ DD conversion on upload/download
//!   - Velocity Verlet integration (second-order, replaces symplectic Euler)
//!   - Source tiling in shared memory for O(N×M) Weber force

pub mod dd;

use cudarc::driver::*;
use cudarc::nvrtc::Ptx;
use rust_decimal::Decimal;
use std::sync::Arc;

use crate::vec3::Vec3;
use crate::torus::TorusBody;
use crate::magnets::SourceElement;
use crate::integrator::BodySnapshot;
use self::dd::{DD, DD3};

// Safety: DD is #[repr(C)] containing two f64s. It's Copy + 'static
// and has a well-defined layout matching the CUDA `dd` struct.
unsafe impl DeviceRepr for DD {}
unsafe impl DeviceRepr for DD3 {}

// PTX modules embedded at compile time (generated by build.rs)
const WEBER_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/weber_kernel.ptx"));
const BOND_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/bond_kernel.ptx"));
const INTEGRATE_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/integrate_kernel.ptx"));
const FIELD_RESIDUAL_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/field_residual_kernel.ptx"));

/// GPU particle state — mirrors IntParticle/GpuParticle in CUDA kernels.
/// All fields are DD (double-double) for 31-digit precision.
#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
pub struct GpuParticle {
    pub pos: DD3,
    pub vel: DD3,
    pub accel: DD3,
    pub mass: DD,
    pub charge: DD,
}

/// GPU source element — mirrors GpuSource in weber_kernel.cu.
/// Includes velocity for rotating magnets (zero for static).
#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
pub struct GpuSource {
    pub pos: DD3,
    pub dl: DD3,
    pub vel: DD3,
}

/// GPU bond — mirrors GpuBond in bond_kernel.cu.
#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
pub struct GpuBond {
    pub i: i32,
    pub j: i32,
    pub rest_length: DD,
}

/// Weber kernel output per particle.
#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
pub struct WeberOutput {
    pub f_total: DD3,
    pub b_field: DD3,
    pub dm_velocity: DD,
    pub bracket_dev: DD,
    pub bracket_coupling: DD,
    pub elastic_coupling: DD,
}

/// F64 probe point for field residual (mirrors F64ProbePoint).
#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
pub struct GpuProbePoint {
    pub pos: [f64; 3],
    pub theta: f64,
    pub phi: f64,
    pub layer: i32,
    pub d_perp: f64,
    pub _pad: f64, // Alignment padding
}

/// F64 probe result (mirrors F64ProbeResult).
#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
pub struct GpuProbeResult {
    pub delta_b: [f64; 3],
    pub b_maxwell: [f64; 3],
    pub f_longitudinal: [f64; 3],
    pub mean_delta_w: f64,
    pub v_sq_over_c_sq: f64,
    pub mean_accel_term: f64,
}

/// F64 source for field residual.
#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
pub struct GpuF64Source {
    pub pos: [f64; 3],
    pub dl: [f64; 3],
}

/// Diagnostic snapshot from GPU Weber computation.
pub struct WeberDiagnostics {
    pub dm_velocity_total: Decimal,
    pub mean_bracket_deviation: Decimal,
    pub mean_bracket_coupling: Decimal,
}

/// Force combine strategy — toggled at runtime via dashboard.
#[derive(Clone, Copy, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CombineMode {
    /// CPU roundtrip: download Weber+bond forces, add on host, upload back
    Cpu,
    /// GPU kernel: combine on device, no data transfer
    Gpu,
    /// Validate: run both, compare results, panic on mismatch
    Validate,
}

/// GPU context: device handle, loaded modules, persistent buffers.
pub struct GpuContext {
    dev: Arc<CudaDevice>,
    // Persistent device buffers
    d_particles: CudaSlice<u8>,
    d_sources: CudaSlice<u8>,
    d_bonds: CudaSlice<u8>,
    d_forces: CudaSlice<u8>,       // Per-particle total force (DD3)
    d_bond_forces: CudaSlice<u8>,  // Per-particle bond force (DD3)
    d_accels: CudaSlice<u8>,       // Per-particle acceleration (DD3)
    d_weber_out: CudaSlice<u8>,    // Per-particle WeberOutput
    // COM reduction buffers
    d_partial_mp: CudaSlice<u8>,
    d_partial_mv: CudaSlice<u8>,
    d_partial_mass: CudaSlice<u8>,
    d_com: CudaSlice<u8>,          // DD3
    d_com_vel: CudaSlice<u8>,      // DD3
    // Angular velocity reduction buffers
    d_partial_num: CudaSlice<u8>,  // Partial Σ m(x'vy' - y'vx') per block
    d_partial_den: CudaSlice<u8>,  // Partial Σ m(x'^2 + y'^2) per block
    // Per-torus counter-rotation support
    d_torus_ids: CudaSlice<u8>,   // i32 per particle
    d_omegas: CudaSlice<u8>,      // DD per torus (small)
    n_tori: usize,
    // Dimensions
    n_particles: usize,
    n_sources: usize,
    n_bonds: usize,
    // Host-side cache for download
    stiffness: DD,
    damping: DD,
    /// Force combine strategy
    pub combine_mode: CombineMode,
}

const BLOCK_SIZE: u32 = 128;

impl GpuContext {
    /// Initialize GPU context: create device, load PTX modules, allocate buffers.
    pub fn new(body: &TorusBody, sources: &[SourceElement]) -> Result<Self, Box<dyn std::error::Error>> {
        let dev = CudaDevice::new(0)?;

        // Load PTX modules
        dev.load_ptx(Ptx::from_src(WEBER_PTX), "weber", &[
            "weber_force_kernel", "newton_force_kernel",
        ])?;
        dev.load_ptx(Ptx::from_src(BOND_PTX), "bond", &[
            "bond_force_kernel", "zero_forces_kernel",
        ])?;
        dev.load_ptx(Ptx::from_src(INTEGRATE_PTX), "integrate", &[
            "half_step_vel_kernel", "update_pos_kernel",
            "compute_accel_kernel", "apply_external_kernel",
            "com_reduce_kernel", "com_finalize_kernel",
            "set_spin_kernel", "reimpose_spin_kernel",
            "set_spin_multi_kernel", "reimpose_spin_multi_kernel",
            "kinetic_energy_kernel",
            "angular_velocity_kernel",
            "combine_weber_bond_kernel", "combine_newton_bond_kernel",
            "add_forces_inplace_kernel",
        ])?;

        let n_particles = body.particles.len();
        let n_sources = sources.len();
        let n_bonds = body.bonds.len();

        let n_blocks = (n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;

        // Convert and upload particles
        let gpu_particles: Vec<GpuParticle> = body.particles.iter().map(|p| {
            GpuParticle {
                pos: DD3::from_vec3(p.pos),
                vel: DD3::from_vec3(p.vel),
                accel: DD3::ZERO,
                mass: DD::from_decimal(p.mass),
                charge: DD::from_decimal(p.charge),
            }
        }).collect();
        let d_particles = Self::upload_bytes(&dev, &gpu_particles)?;

        // Convert and upload sources (including velocity for rotating magnets)
        let gpu_sources: Vec<GpuSource> = sources.iter().map(|s| {
            GpuSource {
                pos: DD3::from_vec3(s.pos),
                dl: DD3::from_vec3(s.dl),
                vel: DD3::from_vec3(s.vel),
            }
        }).collect();
        let d_sources = Self::upload_bytes(&dev, &gpu_sources)?;

        // Convert and upload bonds
        let gpu_bonds: Vec<GpuBond> = body.bonds.iter().map(|b| {
            GpuBond {
                i: b.i as i32,
                j: b.j as i32,
                rest_length: DD::from_decimal(b.rest_length),
            }
        }).collect();
        let d_bonds = Self::upload_bytes(&dev, &gpu_bonds)?;

        // Allocate work buffers
        let dd3_size = std::mem::size_of::<DD3>();
        let weber_out_size = std::mem::size_of::<WeberOutput>();

        let d_forces = dev.alloc_zeros::<u8>(n_particles * dd3_size)?;
        let d_bond_forces = dev.alloc_zeros::<u8>(n_particles * dd3_size)?;
        let d_accels = dev.alloc_zeros::<u8>(n_particles * dd3_size)?;
        let d_weber_out = dev.alloc_zeros::<u8>(n_particles * weber_out_size)?;

        // COM reduction: one partial sum per block
        let dd_size = std::mem::size_of::<DD>();
        let d_partial_mp = dev.alloc_zeros::<u8>(n_blocks as usize * dd3_size)?;
        let d_partial_mv = dev.alloc_zeros::<u8>(n_blocks as usize * dd3_size)?;
        let d_partial_mass = dev.alloc_zeros::<u8>(n_blocks as usize * dd_size)?;
        let d_com = dev.alloc_zeros::<u8>(dd3_size)?;
        let d_com_vel = dev.alloc_zeros::<u8>(dd3_size)?;
        // Angular velocity reduction: one DD per block for numerator and denominator
        let d_partial_num = dev.alloc_zeros::<u8>(n_blocks as usize * dd_size)?;
        let d_partial_den = dev.alloc_zeros::<u8>(n_blocks as usize * dd_size)?;

        let stiffness = DD::from_decimal(body.stiffness);
        let damping = DD::from_decimal(body.damping);

        // Per-torus counter-rotation support
        let n_tori = body.n_tori.max(1);
        let torus_ids_i32: Vec<i32> = body.torus_ids.iter().map(|&id| id as i32).collect();
        let d_torus_ids = Self::upload_bytes(&dev, &torus_ids_i32)?;
        // Omegas buffer: one DD per torus (initially zero)
        let omegas_init: Vec<DD> = vec![DD::ZERO; n_tori];
        let d_omegas = Self::upload_bytes(&dev, &omegas_init)?;

        Ok(GpuContext {
            dev,
            d_particles,
            d_sources,
            d_bonds,
            d_forces,
            d_bond_forces,
            d_accels,
            d_weber_out,
            d_partial_mp,
            d_partial_mv,
            d_partial_mass,
            d_com,
            d_com_vel,
            d_partial_num,
            d_partial_den,
            d_torus_ids,
            d_omegas,
            n_tori,
            n_particles,
            n_sources,
            n_bonds,
            stiffness,
            damping,
            combine_mode: CombineMode::Gpu,
        })
    }

    /// Upload a Vec<T> as raw bytes to the device.
    fn upload_bytes<T: Copy>(dev: &Arc<CudaDevice>, data: &[T]) -> Result<CudaSlice<u8>, Box<dyn std::error::Error>> {
        let bytes = unsafe {
            std::slice::from_raw_parts(
                data.as_ptr() as *const u8,
                data.len() * std::mem::size_of::<T>(),
            )
        };
        let buf = dev.htod_copy(bytes.to_vec())?;
        Ok(buf)
    }

    /// Upload updated body state (positions and velocities) to device.
    pub fn upload_body(&mut self, body: &TorusBody) -> Result<(), Box<dyn std::error::Error>> {
        let gpu_particles: Vec<GpuParticle> = body.particles.iter().map(|p| {
            GpuParticle {
                pos: DD3::from_vec3(p.pos),
                vel: DD3::from_vec3(p.vel),
                accel: DD3::ZERO,
                mass: DD::from_decimal(p.mass),
                charge: DD::from_decimal(p.charge),
            }
        }).collect();
        let bytes = unsafe {
            std::slice::from_raw_parts(
                gpu_particles.as_ptr() as *const u8,
                gpu_particles.len() * std::mem::size_of::<GpuParticle>(),
            )
        };
        self.dev.htod_copy_into(bytes.to_vec(), &mut self.d_particles)?;
        Ok(())
    }

    /// Download particle state from device back to a TorusBody.
    pub fn download_body(&self, template: &TorusBody) -> Result<TorusBody, Box<dyn std::error::Error>> {
        let bytes = self.dev.dtoh_sync_copy(&self.d_particles)?;

        let gpu_particles: &[GpuParticle] = unsafe {
            std::slice::from_raw_parts(
                bytes.as_ptr() as *const GpuParticle,
                self.n_particles,
            )
        };

        let mut body = template.clone();
        for (i, gp) in gpu_particles.iter().enumerate() {
            body.particles[i].pos = gp.pos.to_vec3();
            body.particles[i].vel = gp.vel.to_vec3();
        }
        Ok(body)
    }

    /// Download a BodySnapshot from the current GPU state.
    pub fn download_snapshot(&self, template: &TorusBody) -> Result<BodySnapshot, Box<dyn std::error::Error>> {
        let body = self.download_body(template)?;
        Ok(BodySnapshot::capture(&body))
    }

    /// Download Weber diagnostics from the most recent Weber force computation.
    pub fn download_weber_diagnostics(&self) -> Result<WeberDiagnostics, Box<dyn std::error::Error>> {
        let bytes = self.dev.dtoh_sync_copy(&self.d_weber_out)?;

        let outputs: &[WeberOutput] = unsafe {
            std::slice::from_raw_parts(
                bytes.as_ptr() as *const WeberOutput,
                self.n_particles,
            )
        };

        let mut dm_vel_total = DD::ZERO;
        let mut bracket_dev_total = DD::ZERO;
        let mut bracket_coupling_total = DD::ZERO;

        for out in outputs {
            dm_vel_total = dm_vel_total.add(out.dm_velocity);
            bracket_dev_total = bracket_dev_total.add(out.bracket_dev);
            bracket_coupling_total = bracket_coupling_total.add(out.bracket_coupling);
        }

        let n = DD::from_f64(self.n_particles as f64);
        Ok(WeberDiagnostics {
            dm_velocity_total: dm_vel_total.to_decimal(),
            mean_bracket_deviation: bracket_dev_total.div(n).to_decimal(),
            mean_bracket_coupling: bracket_coupling_total.div(n).to_decimal(),
        })
    }

    /// DEBUG: Download raw accelerations as (f64, f64, f64) tuples.
    pub fn download_accels_raw(&self) -> Result<Vec<(f64, f64, f64)>, Box<dyn std::error::Error>> {
        let bytes = self.dev.dtoh_sync_copy(&self.d_accels)?;
        let accels: &[DD3] = unsafe {
            std::slice::from_raw_parts(
                bytes.as_ptr() as *const DD3,
                self.n_particles,
            )
        };
        Ok(accels.iter().map(|a| (a.x.hi, a.y.hi, a.z.hi)).collect())
    }

    /// DEBUG: Download raw forces as (f64, f64, f64) tuples.
    pub fn download_forces_raw(&self) -> Result<Vec<(f64, f64, f64)>, Box<dyn std::error::Error>> {
        let bytes = self.dev.dtoh_sync_copy(&self.d_forces)?;
        let forces: &[DD3] = unsafe {
            std::slice::from_raw_parts(
                bytes.as_ptr() as *const DD3,
                self.n_particles,
            )
        };
        Ok(forces.iter().map(|f| (f.x.hi, f.y.hi, f.z.hi)).collect())
    }

    /// DEBUG: Download raw particle velocities as (f64, f64, f64) tuples.
    pub fn download_velocities_raw(&self) -> Result<Vec<(f64, f64, f64)>, Box<dyn std::error::Error>> {
        let bytes = self.dev.dtoh_sync_copy(&self.d_particles)?;
        let particles: &[GpuParticle] = unsafe {
            std::slice::from_raw_parts(
                bytes.as_ptr() as *const GpuParticle,
                self.n_particles,
            )
        };
        Ok(particles.iter().map(|p| (p.vel.x.hi, p.vel.y.hi, p.vel.z.hi)).collect())
    }

    /// DEBUG: Download COM velocity from the d_com_vel buffer (must call compute_com first).
    pub fn download_com_vel_raw(&self) -> Result<(f64, f64, f64), Box<dyn std::error::Error>> {
        self.compute_com()?;
        let bytes = self.dev.dtoh_sync_copy(&self.d_com_vel)?;
        let com_vel: &[DD3] = unsafe {
            std::slice::from_raw_parts(
                bytes.as_ptr() as *const DD3,
                1,
            )
        };
        Ok((com_vel[0].x.hi, com_vel[0].y.hi, com_vel[0].z.hi))
    }

    /// Compute COM on GPU (launches reduction kernels).
    fn compute_com(&self) -> Result<(), Box<dyn std::error::Error>> {
        let n_blocks = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;

        let cfg = LaunchConfig {
            grid_dim: (n_blocks, 1, 1),
            block_dim: (BLOCK_SIZE, 1, 1),
            shared_mem_bytes: 0,
        };

        let func = self.dev.get_func("integrate", "com_reduce_kernel")
            .ok_or("com_reduce_kernel not found")?;

        unsafe {
            func.launch(cfg, (
                &self.d_particles,
                &self.d_partial_mp,
                &self.d_partial_mv,
                &self.d_partial_mass,
                self.n_particles as i32,
            ))?;
        }

        // Finalize: single block reduction
        let func2 = self.dev.get_func("integrate", "com_finalize_kernel")
            .ok_or("com_finalize_kernel not found")?;

        let cfg2 = LaunchConfig {
            grid_dim: (1, 1, 1),
            block_dim: (32, 1, 1),  // One warp is enough for < 32 blocks
            shared_mem_bytes: 0,
        };

        unsafe {
            func2.launch(cfg2, (
                &self.d_partial_mp,
                &self.d_partial_mv,
                &self.d_partial_mass,
                &self.d_com,
                &self.d_com_vel,
                n_blocks as i32,
            ))?;
        }

        Ok(())
    }

    /// Compute angular velocity about z-axis entirely on GPU.
    /// Returns omega_z as Decimal. Much cheaper than download_snapshot() —
    /// only transfers 2 scalars per block instead of all particle data.
    pub fn compute_omega_z(&self) -> Result<Decimal, Box<dyn std::error::Error>> {
        // First compute COM (updates d_com, d_com_vel on device)
        self.compute_com()?;

        let n_blocks = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let cfg = LaunchConfig {
            grid_dim: (n_blocks, 1, 1),
            block_dim: (BLOCK_SIZE, 1, 1),
            shared_mem_bytes: 0,
        };

        let func = self.dev.get_func("integrate", "angular_velocity_kernel")
            .ok_or("angular_velocity_kernel not found")?;

        unsafe {
            func.launch(cfg, (
                &self.d_particles,
                &self.d_com,
                &self.d_com_vel,
                &self.d_partial_num,
                &self.d_partial_den,
                self.n_particles as i32,
            ))?;
        }

        // Download partial sums (one DD per block — very small transfer)
        let num_bytes = self.dev.dtoh_sync_copy(&self.d_partial_num)?;
        let den_bytes = self.dev.dtoh_sync_copy(&self.d_partial_den)?;

        let partial_nums: &[DD] = unsafe {
            std::slice::from_raw_parts(
                num_bytes.as_ptr() as *const DD,
                n_blocks as usize,
            )
        };
        let partial_dens: &[DD] = unsafe {
            std::slice::from_raw_parts(
                den_bytes.as_ptr() as *const DD,
                n_blocks as usize,
            )
        };

        // Finalize on CPU (sum the per-block partials)
        let mut num = DD::ZERO;
        let mut den = DD::ZERO;
        for i in 0..n_blocks as usize {
            num = num.add(partial_nums[i]);
            den = den.add(partial_dens[i]);
        }

        if den.hi.abs() < 1e-30 {
            Ok(Decimal::ZERO)
        } else {
            Ok(num.div(den).to_decimal())
        }
    }

    /// Run Weber force kernel.
    fn launch_weber_forces(&self) -> Result<(), Box<dyn std::error::Error>> {
        let n_blocks = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let cfg = LaunchConfig {
            grid_dim: (n_blocks, 1, 1),
            block_dim: (BLOCK_SIZE, 1, 1),
            shared_mem_bytes: 0,
        };

        let func = self.dev.get_func("weber", "weber_force_kernel")
            .ok_or("weber_force_kernel not found")?;

        unsafe {
            func.launch(cfg, (
                &self.d_particles,
                &self.d_sources,
                &self.d_weber_out,
                self.n_particles as i32,
                self.n_sources as i32,
            ))?;
        }

        Ok(())
    }

    /// Run Newton force kernel.
    fn launch_newton_forces(&self) -> Result<(), Box<dyn std::error::Error>> {
        let n_blocks = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let cfg = LaunchConfig {
            grid_dim: (n_blocks, 1, 1),
            block_dim: (BLOCK_SIZE, 1, 1),
            shared_mem_bytes: 0,
        };

        let func = self.dev.get_func("weber", "newton_force_kernel")
            .ok_or("newton_force_kernel not found")?;

        unsafe {
            func.launch(cfg, (
                &self.d_particles,
                &self.d_sources,
                &self.d_forces,
                self.n_particles as i32,
                self.n_sources as i32,
            ))?;
        }

        Ok(())
    }

    /// Run bond force kernel.
    fn launch_bond_forces(&self) -> Result<(), Box<dyn std::error::Error>> {
        // Zero the bond force buffer first
        let n_blocks_p = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let zero_func = self.dev.get_func("bond", "zero_forces_kernel")
            .ok_or("zero_forces_kernel not found")?;

        unsafe {
            zero_func.launch(
                LaunchConfig {
                    grid_dim: (n_blocks_p, 1, 1),
                    block_dim: (BLOCK_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                },
                (&self.d_bond_forces, self.n_particles as i32),
            )?;
        }

        if self.n_bonds == 0 { return Ok(()); }

        let n_blocks_b = (self.n_bonds as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let func = self.dev.get_func("bond", "bond_force_kernel")
            .ok_or("bond_force_kernel not found")?;

        unsafe {
            func.launch(
                LaunchConfig {
                    grid_dim: (n_blocks_b, 1, 1),
                    block_dim: (BLOCK_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                },
                (
                    &self.d_particles,
                    &self.d_bonds,
                    &self.d_bond_forces,
                    self.stiffness,
                    self.damping,
                    self.n_bonds as i32,
                ),
            )?;
        }

        Ok(())
    }

    /// Combine Weber/Newton forces + bond forces + external into total_forces,
    /// then compute accelerations.
    ///
    /// Respects `self.combine_mode`:
    ///   Cpu      — download to host, add, upload (original, safe baseline)
    ///   Gpu      — combine on device via kernel (no data transfer)
    ///   Validate — run GPU then CPU, panic if results differ
    fn combine_forces_and_accel(
        &mut self,
        is_weber: bool,
        thrust: DD3,
        torque_z: DD,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let n_blocks = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let inv_n = DD::from_f64(1.0 / self.n_particles as f64);
        let cfg = LaunchConfig {
            grid_dim: (n_blocks, 1, 1),
            block_dim: (BLOCK_SIZE, 1, 1),
            shared_mem_bytes: 0,
        };

        let use_gpu = self.combine_mode == CombineMode::Gpu || self.combine_mode == CombineMode::Validate;
        let use_cpu = self.combine_mode == CombineMode::Cpu || self.combine_mode == CombineMode::Validate;

        // --- GPU path: combine on device ---
        if use_gpu {
            if is_weber {
                let func = self.dev.get_func("integrate", "combine_weber_bond_kernel")
                    .ok_or("combine_weber_bond_kernel not found")?;
                unsafe {
                    func.launch(cfg, (
                        &self.d_weber_out,
                        &self.d_bond_forces,
                        &self.d_forces,
                        self.n_particles as i32,
                    ))?;
                }
            } else {
                // Newton: d_forces already has EM forces, add bond_forces in-place
                let func = self.dev.get_func("integrate", "add_forces_inplace_kernel")
                    .ok_or("add_forces_inplace_kernel not found")?;
                unsafe {
                    func.launch(cfg, (
                        &self.d_forces,
                        &self.d_bond_forces,
                        self.n_particles as i32,
                    ))?;
                }
            }
        }

        // --- CPU path: download, add on host, upload ---
        if use_cpu {
            let bond_bytes = self.dev.dtoh_sync_copy(&self.d_bond_forces)?;
            let bond_forces: &[DD3] = unsafe {
                std::slice::from_raw_parts(
                    bond_bytes.as_ptr() as *const DD3,
                    self.n_particles,
                )
            };

            let combined: Vec<DD3> = if is_weber {
                let weber_bytes = self.dev.dtoh_sync_copy(&self.d_weber_out)?;
                let weber_outs: &[WeberOutput] = unsafe {
                    std::slice::from_raw_parts(
                        weber_bytes.as_ptr() as *const WeberOutput,
                        self.n_particles,
                    )
                };
                (0..self.n_particles).map(|i| {
                    weber_outs[i].f_total.add(bond_forces[i])
                }).collect()
            } else {
                let em_bytes = self.dev.dtoh_sync_copy(&self.d_forces)?;
                let em_forces: &[DD3] = unsafe {
                    std::slice::from_raw_parts(
                        em_bytes.as_ptr() as *const DD3,
                        self.n_particles,
                    )
                };
                (0..self.n_particles).map(|i| {
                    em_forces[i].add(bond_forces[i])
                }).collect()
            };

            // Validate mode: compare GPU result with CPU result
            if self.combine_mode == CombineMode::Validate {
                let gpu_bytes = self.dev.dtoh_sync_copy(&self.d_forces)?;
                let gpu_forces: &[DD3] = unsafe {
                    std::slice::from_raw_parts(
                        gpu_bytes.as_ptr() as *const DD3,
                        self.n_particles,
                    )
                };
                for i in 0..self.n_particles {
                    let cpu = &combined[i];
                    let gpu = &gpu_forces[i];
                    let dx = (cpu.x.hi - gpu.x.hi).abs();
                    let dy = (cpu.y.hi - gpu.y.hi).abs();
                    let dz = (cpu.z.hi - gpu.z.hi).abs();
                    let tol = 1e-28;
                    if dx > tol || dy > tol || dz > tol {
                        panic!(
                            "GPU/CPU combine mismatch at particle {}: CPU=({},{},{}), GPU=({},{},{}), diff=({},{},{})",
                            i, cpu.x.hi, cpu.y.hi, cpu.z.hi,
                            gpu.x.hi, gpu.y.hi, gpu.z.hi, dx, dy, dz
                        );
                    }
                }
            }

            // In CPU-only mode, upload the CPU result
            if self.combine_mode == CombineMode::Cpu {
                let force_bytes = unsafe {
                    std::slice::from_raw_parts(
                        combined.as_ptr() as *const u8,
                        combined.len() * std::mem::size_of::<DD3>(),
                    )
                };
                self.dev.htod_copy_into(force_bytes.to_vec(), &mut self.d_forces)?;
            }
        }

        // Apply external forces (thrust + torque)
        self.compute_com()?;

        let ext_func = self.dev.get_func("integrate", "apply_external_kernel")
            .ok_or("apply_external_kernel not found")?;

        unsafe {
            ext_func.launch(
                LaunchConfig {
                    grid_dim: (n_blocks, 1, 1),
                    block_dim: (BLOCK_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                },
                (
                    &self.d_particles,
                    &self.d_forces,
                    &self.d_com,
                    thrust,
                    torque_z,
                    inv_n,
                    self.n_particles as i32,
                ),
            )?;
        }

        // Compute accelerations: a = F / m
        let accel_func = self.dev.get_func("integrate", "compute_accel_kernel")
            .ok_or("compute_accel_kernel not found")?;

        unsafe {
            accel_func.launch(
                LaunchConfig {
                    grid_dim: (n_blocks, 1, 1),
                    block_dim: (BLOCK_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                },
                (
                    &self.d_particles,
                    &self.d_forces,
                    &self.d_accels,
                    self.n_particles as i32,
                ),
            )?;
        }

        Ok(())
    }

    /// Velocity Verlet integration step for Weber mechanics.
    ///
    /// 1. v(t+dt/2) = v(t) + a(t)*dt/2
    /// 2. x(t+dt) = x(t) + v(t+dt/2)*dt
    /// 3. Compute forces at new positions
    /// 4. v(t+dt) = v(t+dt/2) + a(t+dt)*dt/2
    pub fn step_weber(
        &mut self,
        thrust: Vec3,
        torque_z: Decimal,
        dt: Decimal,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let dd_dt = DD::from_decimal(dt);
        let half_dt = dd_dt.mul_d(0.5);
        let dd_thrust = DD3::from_vec3(thrust);
        let dd_torque = DD::from_decimal(torque_z);

        let n_blocks = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let cfg = LaunchConfig {
            grid_dim: (n_blocks, 1, 1),
            block_dim: (BLOCK_SIZE, 1, 1),
            shared_mem_bytes: 0,
        };

        // Step 1: half-step velocity
        let half_vel_func = self.dev.get_func("integrate", "half_step_vel_kernel")
            .ok_or("half_step_vel_kernel not found")?;
        unsafe {
            half_vel_func.launch(cfg, (
                &self.d_particles,
                &self.d_accels,
                half_dt,
                self.n_particles as i32,
            ))?;
        }

        // Step 2: update positions
        let pos_func = self.dev.get_func("integrate", "update_pos_kernel")
            .ok_or("update_pos_kernel not found")?;
        unsafe {
            pos_func.launch(cfg, (
                &self.d_particles,
                dd_dt,
                self.n_particles as i32,
            ))?;
        }

        // Step 3: compute forces at new positions
        self.launch_weber_forces()?;
        self.launch_bond_forces()?;
        self.combine_forces_and_accel(true, dd_thrust, dd_torque)?;

        // Step 4: second half-step velocity
        let half_vel_func2 = self.dev.get_func("integrate", "half_step_vel_kernel")
            .ok_or("half_step_vel_kernel not found")?;
        unsafe {
            half_vel_func2.launch(cfg, (
                &self.d_particles,
                &self.d_accels,
                half_dt,
                self.n_particles as i32,
            ))?;
        }

        Ok(())
    }

    /// Velocity Verlet step for Newtonian mechanics (no Weber corrections).
    pub fn step_newton(
        &mut self,
        thrust: Vec3,
        torque_z: Decimal,
        dt: Decimal,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let dd_dt = DD::from_decimal(dt);
        let half_dt = dd_dt.mul_d(0.5);
        let dd_thrust = DD3::from_vec3(thrust);
        let dd_torque = DD::from_decimal(torque_z);

        let n_blocks = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let cfg = LaunchConfig {
            grid_dim: (n_blocks, 1, 1),
            block_dim: (BLOCK_SIZE, 1, 1),
            shared_mem_bytes: 0,
        };

        // Step 1: half-step velocity
        let half_vel_func = self.dev.get_func("integrate", "half_step_vel_kernel")
            .ok_or("half_step_vel_kernel not found")?;
        unsafe {
            half_vel_func.launch(cfg, (
                &self.d_particles,
                &self.d_accels,
                half_dt,
                self.n_particles as i32,
            ))?;
        }

        // Step 2: update positions
        let pos_func = self.dev.get_func("integrate", "update_pos_kernel")
            .ok_or("update_pos_kernel not found")?;
        unsafe {
            pos_func.launch(cfg, (
                &self.d_particles,
                dd_dt,
                self.n_particles as i32,
            ))?;
        }

        // Step 3: compute forces at new positions
        self.launch_newton_forces()?;
        self.launch_bond_forces()?;
        self.combine_forces_and_accel(false, dd_thrust, dd_torque)?;

        // Step 4: second half-step velocity
        let half_vel_func2 = self.dev.get_func("integrate", "half_step_vel_kernel")
            .ok_or("half_step_vel_kernel not found")?;
        unsafe {
            half_vel_func2.launch(cfg, (
                &self.d_particles,
                &self.d_accels,
                half_dt,
                self.n_particles as i32,
            ))?;
        }

        Ok(())
    }

    /// Set rigid spin about z-axis.
    pub fn set_spin(&self, omega_z: Decimal) -> Result<(), Box<dyn std::error::Error>> {
        self.compute_com()?;

        let n_blocks = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let func = self.dev.get_func("integrate", "set_spin_kernel")
            .ok_or("set_spin_kernel not found")?;

        unsafe {
            func.launch(
                LaunchConfig {
                    grid_dim: (n_blocks, 1, 1),
                    block_dim: (BLOCK_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                },
                (
                    &self.d_particles,
                    &self.d_com,
                    DD::from_decimal(omega_z),
                    self.n_particles as i32,
                ),
            )?;
        }

        Ok(())
    }

    /// Reimpose rigid-body rotation while preserving COM velocity.
    /// v_i = v_com + omega_z × (r_i - com)
    ///
    /// This eliminates bond-induced spin decay (a numerical artifact of
    /// discretized bonded-particle rotation) while keeping the translational
    /// signal intact for coupling measurements.
    pub fn reimpose_rigid_rotation(&self, omega_z: Decimal) -> Result<(), Box<dyn std::error::Error>> {
        self.compute_com()?;

        let n_blocks = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let func = self.dev.get_func("integrate", "reimpose_spin_kernel")
            .ok_or("reimpose_spin_kernel not found")?;

        unsafe {
            func.launch(
                LaunchConfig {
                    grid_dim: (n_blocks, 1, 1),
                    block_dim: (BLOCK_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                },
                (
                    &self.d_particles,
                    &self.d_com,
                    &self.d_com_vel,
                    DD::from_decimal(omega_z),
                    self.n_particles as i32,
                ),
            )?;
        }

        Ok(())
    }

    /// Per-torus set_spin for counter-rotation.
    /// omegas[torus_id] gives the angular velocity for each torus.
    pub fn set_spin_multi(&mut self, omegas: &[Decimal]) -> Result<(), Box<dyn std::error::Error>> {
        self.compute_com()?;

        // Upload per-torus omegas
        let dd_omegas: Vec<DD> = omegas.iter().map(|&o| DD::from_decimal(o)).collect();
        let omega_bytes = unsafe {
            std::slice::from_raw_parts(
                dd_omegas.as_ptr() as *const u8,
                dd_omegas.len() * std::mem::size_of::<DD>(),
            )
        };
        self.dev.htod_copy_into(omega_bytes.to_vec(), &mut self.d_omegas)?;

        let n_blocks = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let func = self.dev.get_func("integrate", "set_spin_multi_kernel")
            .ok_or("set_spin_multi_kernel not found")?;

        unsafe {
            func.launch(
                LaunchConfig {
                    grid_dim: (n_blocks, 1, 1),
                    block_dim: (BLOCK_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                },
                (
                    &self.d_particles,
                    &self.d_com,
                    &self.d_torus_ids,
                    &self.d_omegas,
                    self.n_particles as i32,
                ),
            )?;
        }

        Ok(())
    }

    /// Per-torus reimpose rigid rotation (counter-rotation support).
    /// Preserves COM velocity while applying per-torus omega.
    pub fn reimpose_rigid_rotation_multi(&mut self, omegas: &[Decimal]) -> Result<(), Box<dyn std::error::Error>> {
        self.compute_com()?;

        // Upload per-torus omegas
        let dd_omegas: Vec<DD> = omegas.iter().map(|&o| DD::from_decimal(o)).collect();
        let omega_bytes = unsafe {
            std::slice::from_raw_parts(
                dd_omegas.as_ptr() as *const u8,
                dd_omegas.len() * std::mem::size_of::<DD>(),
            )
        };
        self.dev.htod_copy_into(omega_bytes.to_vec(), &mut self.d_omegas)?;

        let n_blocks = (self.n_particles as u32 + BLOCK_SIZE - 1) / BLOCK_SIZE;
        let func = self.dev.get_func("integrate", "reimpose_spin_multi_kernel")
            .ok_or("reimpose_spin_multi_kernel not found")?;

        unsafe {
            func.launch(
                LaunchConfig {
                    grid_dim: (n_blocks, 1, 1),
                    block_dim: (BLOCK_SIZE, 1, 1),
                    shared_mem_bytes: 0,
                },
                (
                    &self.d_particles,
                    &self.d_com,
                    &self.d_com_vel,
                    &self.d_torus_ids,
                    &self.d_omegas,
                    self.n_particles as i32,
                ),
            )?;
        }

        Ok(())
    }

    /// Initialize acceleration estimates by computing forces at initial positions.
    /// Must be called once before the first Verlet step.
    pub fn init_accels(
        &mut self,
        is_weber: bool,
        thrust: Vec3,
        torque_z: Decimal,
    ) -> Result<(), Box<dyn std::error::Error>> {
        if is_weber {
            self.launch_weber_forces()?;
        } else {
            self.launch_newton_forces()?;
        }
        self.launch_bond_forces()?;
        let dd_thrust = DD3::from_vec3(thrust);
        let dd_torque = DD::from_decimal(torque_z);
        self.combine_forces_and_accel(is_weber, dd_thrust, dd_torque)?;
        Ok(())
    }
}

/// Field residual GPU context (separate, uses f64 kernels).
pub struct FieldResidualGpu {
    dev: Arc<CudaDevice>,
    d_probes: CudaSlice<u8>,
    d_sources: CudaSlice<u8>,
    d_results: CudaSlice<u8>,
    n_probes: usize,
    n_sources: usize,
}

impl FieldResidualGpu {
    /// Create field residual GPU context.
    pub fn new(
        probes: &[(f64, f64, f64, f64, f64, usize, f64)], // (x,y,z, theta,phi, layer, d_perp)
        sources: &[(f64, f64, f64, f64, f64, f64)],        // (px,py,pz, dlx,dly,dlz)
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let dev = CudaDevice::new(0)?;

        dev.load_ptx(Ptx::from_src(FIELD_RESIDUAL_PTX), "field_residual", &[
            "field_residual_kernel",
        ])?;

        let gpu_probes: Vec<GpuProbePoint> = probes.iter().map(|&(x,y,z,theta,phi,layer,d_perp)| {
            GpuProbePoint {
                pos: [x, y, z],
                theta,
                phi,
                layer: layer as i32,
                d_perp,
                _pad: 0.0,
            }
        }).collect();

        let gpu_sources: Vec<GpuF64Source> = sources.iter().map(|&(px,py,pz,dlx,dly,dlz)| {
            GpuF64Source {
                pos: [px, py, pz],
                dl: [dlx, dly, dlz],
            }
        }).collect();

        let n_probes = gpu_probes.len();
        let n_sources = gpu_sources.len();

        let d_probes = Self::upload_bytes(&dev, &gpu_probes)?;
        let d_sources = Self::upload_bytes(&dev, &gpu_sources)?;
        let d_results = dev.alloc_zeros::<u8>(n_probes * std::mem::size_of::<GpuProbeResult>())?;

        Ok(FieldResidualGpu {
            dev,
            d_probes,
            d_sources,
            d_results,
            n_probes,
            n_sources,
        })
    }

    fn upload_bytes<T: Copy>(dev: &Arc<CudaDevice>, data: &[T]) -> Result<CudaSlice<u8>, Box<dyn std::error::Error>> {
        let bytes = unsafe {
            std::slice::from_raw_parts(
                data.as_ptr() as *const u8,
                data.len() * std::mem::size_of::<T>(),
            )
        };
        let buf = dev.htod_copy(bytes.to_vec())?;
        Ok(buf)
    }

    /// Compute field residual for all probes at given omega and c_eff_sq.
    pub fn compute(
        &self,
        omega: f64,
        c_eff_sq: f64,
    ) -> Result<Vec<GpuProbeResult>, Box<dyn std::error::Error>> {
        let n_blocks = (self.n_probes as u32 + 256 - 1) / 256;

        let func = self.dev.get_func("field_residual", "field_residual_kernel")
            .ok_or("field_residual_kernel not found")?;

        unsafe {
            func.launch(
                LaunchConfig {
                    grid_dim: (n_blocks, 1, 1),
                    block_dim: (256, 1, 1),
                    shared_mem_bytes: 0,
                },
                (
                    &self.d_probes,
                    &self.d_sources,
                    &self.d_results,
                    omega,
                    c_eff_sq,
                    self.n_probes as i32,
                    self.n_sources as i32,
                ),
            )?;
        }

        let bytes = self.dev.dtoh_sync_copy(&self.d_results)?;
        let results: &[GpuProbeResult] = unsafe {
            std::slice::from_raw_parts(
                bytes.as_ptr() as *const GpuProbeResult,
                self.n_probes,
            )
        };

        Ok(results.to_vec())
    }
}
